name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    name: Check with ${{matrix.features}} on ${{matrix.os}}-latest
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable]
        os: [ubuntu]
        features: [--all-features, --no-default-features]
    steps:
      - uses: actions/checkout@main
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets ${{matrix.features}}

  test:
    name: Test Rust ${{matrix.toolchain}} on ${{matrix.os}}-latest
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, nightly]
        os: [ubuntu]
    steps:
      - uses: actions/checkout@main
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

  clippy:
    name: Clippy ${{matrix.toolchain}} on ${{matrix.os}}-latest
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [nightly]
        os: [ubuntu]
    steps:
      - uses: actions/checkout@main
      - name: Install minimal nightly with clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.toolchain}}
          components: clippy
          override: true
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all -- -D clippy::all -D warnings

  rustfmt:
    name: rustfmt ${{matrix.toolchain}} on ${{matrix.os}}-latest
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [nightly]
        os: [ubuntu]
    steps:
      - uses: actions/checkout@main
      - name: Install minimal nightly with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.toolchain}}
          components: rustfmt
          override: true
      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  no-std:
    name: no-std build with ${{matrix.toolchain}} on ${{matrix.os}}-latest
    runs-on: ${{matrix.os}}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        toolchain: [stable, nightly]
        target:
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@main
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - run: rustup target add ${{matrix.target}}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --no-default-features --target ${{matrix.target}}
